command:
  - uv
  - run
  - uvicorn
  - small_examples.async_llm_app:app
  - --host
  - 0.0.0.0
  - --port
  - ${DATABRICKS_APP_PORT}
# Optional environment variables to override defaults
env:
  - name: LLM_ENDPOINT_NAME
    value: databricks-meta-llama-3-3-70b-instruct
  - name: VECTOR_SEARCH_ENDPOINT_NAME
    value: one-env-shared-endpoint-3
  - name: VECTOR_SEARCH_INDEX_NAME
    value: shm.multimodal.index
