command:
  - python
  - -m
  - uvicorn
  - async_llm_app:app
env:
  - name: LLM_ENDPOINT_NAME
    value: databricks-meta-llama-3-3-70b-instruct
  - name: VECTOR_SEARCH_ENDPOINT_NAME
    value: one-env-shared-endpoint-3
  - name: VECTOR_SEARCH_INDEX_NAME
    value: shm.multimodal.index
  - name: PAT
    valueFrom: db_token