llm_max_tokens: 3000
llm_temperature: 0.1
vs_endpoint: one-env-shared-endpoint-1
vs_index_name: shm.dbdemos_llm_rag.databricks_documentation_shared_index
score_threshold: 0.1
num_results: 3
url_picklist: 
  - 'https://docs.databricks.com/en/machine-learning/mlops/llmops.html'
  - 'https://docs.databricks.com/en/sql/language-manual/functions/ai_summarize.html'
  - 'https://docs.databricks.com/en/sql/language-manual/functions/mask.html'
  - 'https://docs.databricks.com/en/archive/runtime-release-notes/7.4.html'
  - 'https://docs.databricks.com/en/admin/workspace-settings/dbfs-browser.html'
  - 'https://docs.databricks.com/en/release-notes/product/2019/october.html'
  - 'https://docs.databricks.com/en/delta-live-tables/run-schedule-updates.html'
  - 'https://docs.databricks.com/en/partners/ingestion/syncsort.html'
  - 'https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-having.html'
  - 'https://docs.databricks.com/en/error-messages/copy-into-syntax-error-error-class.html'
url_extraction_prompt: > 
  Extract the url of the technologies referenced in the question by using the provided list of urls. List of technologies: {url_picklist}. Strictly only extract and print url name from the question. Do not print anything extra

  Example Question: What us machine-learning? 
  Example Output: https://docs.databricks.com/en/machine-learning/mlops/llmops.html

  Question: {question}
retrieval_prompt: >
  You are a document assistant for Databricks technology. Based on previous documents given in the context below, you answer technical questions about Databricks products. If the question is not related to these topics, kindly decline to answer. If you don't know the answer, just say that you don't know, don't try to make up an answer. Keep the answer concise, do not repeat the prompt.

  Use the following pieces of context from existing documents to answer the question at the end:

  {context}

  Question: {question}
  Answer: